#    klassi-js
#    Copyright © 2016 - Larry Goddard
#
#    Javascript Node CircleCI 2.0 configuration file
#    Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2.1

references:
  filter_ignore_wip_branches: &filter_ignore_wip_branches
    filters:
      branches:
        ignore:
          - /[a-z]{2}_wip.*/ # wip branches with initials prefix, e.g. mw_wip
          - /wip\/.*/ # wip branches with wip/ prefix, e.g. wip/foo
          - /poc\/.*/ # poc branches with poc/ prefix, e.g. poc/bar

  filter_only_integration_branches: &filter_only_integration_branches
    filters:
      branches:
        only:
          - develop # git flow production branch
          - /testfix\/.*/ # testfix branches with testfix/ prefix. e.g. testfix/foo

  filter_only_releasable_branches: &filter_only_releasable_branches
    filters:
      branches:
        only:
          - master # git flow production branch
          - main # git flow production branch
          - /hotfix\/.*/ # git flow hotfix branches
          - /release\/.*/ # git flow release branches

jobs:
  ###########################################
  # Acceptance test base configuration      #
  ###########################################
  acceptance_test_base: &acceptance_test_base
    docker:
      - image: cimg/node:14.19.0-browsers
    resource_class: small
    parallelism: 2
    working_directory: ~/klassiG
    steps:
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config

      - run:
          name: Checkout klassi framework repo
          command: git clone git@github.com:larryg01/klassi-js.git

      - run:
          name: Check out the working branch
          path: ~/klassiG/klassi-js
          command: git checkout ${CIRCLE_BRANCH}

      - run:
          name: Setting up tmp Dir for split files
          command: mkdir ~/klassiG/klassi-js/tmp

      - run:
          name: Setting up parallelism and splitting features files
          path: ~/klassiG/klassi-js
          command: |
            echo $(circleci tests glob "features/**/*.feature")
            TEST_FILES=$(circleci tests glob "features/**/*.feature" | circleci tests split > tmp/test-to-run | xargs -n 1 echo)
            echo $TEST_FILES

      - run:
          name: Generate dependency cache key
          command: cat ~/klassiG/klassi-js/package.json > CACHE_KEY

      - restore_cache:
          key: klassi-yarn-cache-v1{{ checksum "CACHE_KEY" }}

      - run:
          name: Install klassi framework dependencies
          path: ~/klassiG/klassi-js
          command: yarn install

      # Save yarn cache, don't include node modules because we end up with an
      # archive so large that unarchiving takes longer than the yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
            - ~/klassiG/klassi-js/yarn.lock
          key: klassi-yarn-cache-v1{{ checksum "CACHE_KEY" }}

      - run:
          name: Run acceptance tests
          path: ~/klassiG/klassi-js
          command: |
            circleci tests glob "features/**/*.feature" | circleci tests split > tmp/test-to-run | xargs -n 1 echo
            TEST_FILES=$(cat tmp/test-to-run | xargs | sed -e 's/ /,/g')
            echo $TEST_FILES
            yarn cilt${STAGE} ${BROWSER} --featureFiles $TEST_FILES

      - store_artifacts:
          path: ~/klassiG/klassi-js/artifacts

      - store_test_results:
          path: ~/klassiG/klassi-js/reports

  acceptance_test_chrome:
    <<: *acceptance_test_base
    environment: { BROWSER: 'chrome', STAGE: 'dev' }

  acceptance_test_firefox:
    <<: *acceptance_test_base
    environment: { BROWSER: 'firefox', STAGE: 'dev' }

workflows:
  version: 2
  build_and_test:
    jobs:
      - acceptance_test_firefox:
          <<: *filter_only_integration_branches

      - acceptance_test_chrome:
          <<: *filter_only_integration_branches
